### ISSUE TITLE
ADD: Create Opt-in checkbox for being mentioned on the show.

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/Python-Community-News#111]
Create Opt-in checkbox for if the person would be okay with being mentioned in the show as a topic or event contributor.

This can be added to the options along with the have read and agree to the code of conduct.

**Comment by kjaymiller** [comment]
in the `terms` section in both [add_topic.yaml](https://github.com/kjaymiller/Python-Community-News/tree/main/.github/[ISSUE_TEMPLATE]/add_topic.yaml) and [Add Conference.yaml](https://github.com/kjaymiller/Python-Community-News/tree/main/.github/[ISSUE_TEMPLATE]/Add%20Conference.yaml)

```
 - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
```

- change the `Label` to "Terms and Approvals"
- change the `description` to "Please check all of the appropriate and desired options"
- under options add a `label` with the text "I allow the hosts to mention me as a contributor of the content above"
